name: Build

on: [push, pull_request]

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [18.x, 20.x, 22.x]
        steps:
            - uses: actions/checkout@v5
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node-version }}
            - name: Install dependencies
              run: npm ci
            - name: Build
              run: npm run --if-present build
            - name: Test
              if: ${{ matrix.node-version == '22.x' }}
              run: npm exec ava

    vue:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                vue-version: [2.x, 3.x]
        steps:
            - uses: actions/checkout@v5
            - name: Use Node.js 20.x
              uses: actions/setup-node@v4
              with:
                  node-version: 20.x
            - name: Install dependencies
              run: |
                  npm ci
                  npm install -w @forsakringskassan/eslint-config-vue vue@${{ matrix.vue-version }}
            - name: Disable vue/no-multiple-template-root (vue 2 only)
              if: matrix.vue-version == '2.x'
              run: |
                  echo '{ "rules": { "vue/no-multiple-template-root": "off" } }' > packages/eslint-config-vue/.eslintrc.json
            - name: ESLint
              run: npm run eslint
